name: py39
channels:
  - gurobi
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - anyio=3.7.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=6.0.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - cffi=1.15.0
  - contourpy=1.0.5
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - fftw=3.3.9
  - flit-core=3.9.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gurobi=11.0.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.7.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jupyter=1.1.1
  - jupyter_console=6.6.3
  - jupyter_core=5.1.1
  - jupyter_events=0.6.3
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.5
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.4
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=10.0.1
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libpq=12.9
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.4
  - mapclassify=2.5.0
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - matplotlib-scalebar=0.8.1
  - mistune=2.0.5
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.4.0
  - nbconvert-core=7.4.0
  - nbconvert-pandoc=7.4.0
  - nbformat=5.8.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1w
  - packaging=22.0
  - pandas=1.5.2
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - ply=3.11
  - prometheus_client=0.17.0
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.17.1
  - python_abi=3.9
  - pytz=2022.7
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.6.1
  - qtpy=2.4.1
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scipy=1.9.3
  - seaborn=0.12.2
  - send2trash=1.8.2
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.1
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.7.1
  - typing_extensions=4.6.2
  - tzdata=2022g
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=4.0.13
  - xz=5.2.10
  - y-py=0.6.2
  - yaml=0.2.5
  - ypy-websocket=0.8.4
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==22.2.0
      - babel==2.17.0
      - cchardet==2.1.7
      - charset-normalizer==3.4.1
      - ckanapi==4.7
      - click==8.1.3
      - click-plugins==1.1.1
      - cligj==0.7.2
      - comm==0.2.2
      - docopt==0.6.2
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.2
      - fiona==1.8.22
      - fqdn==1.5.1
      - geodatasets==2023.3.0
      - geopandas==0.12.2
      - git-filter-repo==2.45.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - isoweek==1.3.3
      - joblib==1.2.0
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-server==2.27.3
      - macposts==0.5.1
      - munch==2.5.0
      - openpyxl==3.1.2
      - overrides==7.7.0
      - partridge==1.1.1
      - pip==25.0.1
      - pooch==1.8.0
      - pyproj==3.4.1
      - python-json-logger==3.3.0
      - python-slugify==7.0.0
      - pyyaml==6.0
      - pyzmq==26.2.1
      - referencing==0.36.2
      - rpds-py==0.23.1
      - scikit-learn==1.2.0
      - shapely==2.0.0
      - text-unidecode==1.3
      - threadpoolctl==3.1.0
      - tomli==2.2.1
      - types-python-dateutil==2.9.0.20241206
      - uri-template==1.3.0
      - urllib3==1.26.14
      - webcolors==24.11.1
      - websocket-client==1.8.0
